// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    partial class ApiDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Url", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortenedUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OriginalUrl")
                        .IsUnique();

                    b.HasIndex("ShortenedUrl")
                        .IsUnique();

                    b.ToTable("Urls");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "PQ",
                            CreatedAt = new DateTime(2024, 2, 10, 16, 11, 3, 515, DateTimeKind.Utc).AddTicks(6717),
                            ExpireAt = new DateTime(2024, 2, 10, 16, 16, 3, 515, DateTimeKind.Utc).AddTicks(6719),
                            OriginalUrl = "https://www.youtube.com/",
                            ShortenedUrl = "https://localhost:7167/PQ"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "Mn",
                            CreatedAt = new DateTime(2024, 2, 10, 16, 11, 3, 515, DateTimeKind.Utc).AddTicks(6749),
                            ExpireAt = new DateTime(2024, 2, 10, 16, 16, 3, 515, DateTimeKind.Utc).AddTicks(6750),
                            OriginalUrl = "https://learn.microsoft.com/",
                            ShortenedUrl = "https://localhost:7167/Mn"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "wQ",
                            CreatedAt = new DateTime(2024, 2, 10, 16, 11, 3, 515, DateTimeKind.Utc).AddTicks(6775),
                            ExpireAt = new DateTime(2024, 2, 10, 16, 16, 3, 515, DateTimeKind.Utc).AddTicks(6776),
                            OriginalUrl = "https://www.linkedin.com/feed/",
                            ShortenedUrl = "https://localhost:7167/wQ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
